### ISSUE TITLE
ink still wet, code already broken

### ISSUE THREAD

**Issue by mlewis1973** [reginabarzilaygroup/Sybil#20]
probably taken out by changes in scikit-learn
too bad there isn't a requirements.txt or a Dockerfile with a hint 
of what version of scikit-learn was originally used...

>>> scores = model.predict( [ serie] )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mlewis/anaconda3/envs/sybil/lib/python3.9/site-packages/sybil/model.py", line 289, in predict
    calib_scores = self._calibrate(scores).tolist()
  File "/home/mlewis/anaconda3/envs/sybil/lib/python3.9/site-packages/sybil/model.py", line 222, in _calibrate
    probs = self.calibrator["Year{}".format(YEAR + 1)].predict_proba(probs)[
  File "/home/mlewis/anaconda3/envs/sybil/lib/python3.9/site-packages/sklearn/calibration.py", line 500, in predict_proba
    proba = calibrated_classifier.predict_proba(X)
  File "/home/mlewis/anaconda3/envs/sybil/lib/python3.9/site-packages/sklearn/calibration.py", line 791, in predict_proba
    pred_method, method_name = _get_prediction_method(self.estimator)
AttributeError: '_CalibratedClassifier' object has no attribute 'estimator'

**Comment by mlewis1973** [comment]
requirements.txt is in docs/
