### ISSUE TITLE
four error in running python regression_test.py

### ISSUE THREAD

**Issue by liujun0621** [reginabarzilaygroup/Sybil#47]
root@autodl-container-959a4bb496-3d0d2478:~/Sybil-main/tests# python regression_test.py
E

EEAbout to test 26 series
Downloading models to /root/.sybil/
E
======================================================================
ERROR: test_demo_data (__main__.TestPredict)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fe3753fe050>, 'Connection to www.dropbox.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /sh/addq480zyguxbbg/AACJRVsKDL0gpq-G9o3rfCBQa?dl=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe3753fe050>, 'Connection to www.dropbox.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Sybil-main/tests/regression_test.py", line 136, in test_demo_data
    download_and_extract_zip(zip_file_name, cache_dir, demo_data_url, demo_data_dir)
  File "/root/Sybil-main/tests/regression_test.py", line 86, in download_and_extract_zip
    response = requests.get(url)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /sh/addq480zyguxbbg/AACJRVsKDL0gpq-G9o3rfCBQa?dl=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe3753fe050>, 'Connection to www.dropbox.com timed out. (connect timeout=None)'))

======================================================================
ERROR: test_calibrator (__main__.TestPredictionRegression)
Test the calibrator against previous known calibrations.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fe3753fe080>, 'Connection to www.dropbox.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /scl/fi/2fx6ukmozia7y3u8mie97/sybil_ensemble_v1.4.0_calibrations.json?rlkey=tquids9qo4mkkuf315nqdq0o7&dl=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe3753fe080>, 'Connection to www.dropbox.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Sybil-main/tests/regression_test.py", line 398, in test_calibrator
    download_file(reference_calibrations_url, default_baseline_path)
  File "/root/Sybil-main/tests/regression_test.py", line 63, in download_file
    response = requests.get(url)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /scl/fi/2fx6ukmozia7y3u8mie97/sybil_ensemble_v1.4.0_calibrations.json?rlkey=tquids9qo4mkkuf315nqdq0o7&dl=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe3753fe080>, 'Connection to www.dropbox.com timed out. (connect timeout=None)'))

======================================================================
ERROR: test_compare_predict_scores (__main__.TestPredictionRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Sybil-main/tests/regression_test.py", line 340, in test_compare_predict_scores
    with open(baseline_preds_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Sybil-main/tests/nlst_predictions/nlst_predictions_ark_v1.4.0.json'

======================================================================
ERROR: test_nlst_predict (__main__.TestPredictionRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Sybil-main/tests/regression_test.py", line 256, in test_nlst_predict
    model = Sybil(model_name)
  File "/root/Sybil-main/sybil/model.py", line 161, in __init__
    name_or_path, calibrator_path = download_sybil(name_or_path, cache)
  File "/root/Sybil-main/sybil/model.py", line 105, in download_sybil
    download_and_extract(CHECKPOINT_URL, cache)
  File "/root/Sybil-main/sybil/model.py", line 111, in download_and_extract
    resp = urlopen(remote_model_url)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

----------------------------------------------------------------------
Ran 4 tests in 393.370s

FAILED (errors=4)

**Comment by jsilter** [comment]
Please check your internet connection and try again

**Comment by liujun0621** [comment]
network problem，thanks
how to generate json?
for example,dicom format:
 |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.191156082608953483831630939833.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.191826888183867106552732676500.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.193305964525230567532561636472.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.193806257361655711211282853784.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.194009576889347155850865953760.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.194798450357340301655671754479.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.195157114822073039054677026555.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.195488996384185448140670261352.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.195920911070246765367343298577.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.198303985180439775013173219624.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.198701739119968322922595169462.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.199070941515537039158357223805.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.204085133817913637632997982836.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.204780610993941279359359302612.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.207445141242694964071384624013.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.212437100215236560019533712179.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.212871949911938192104647017750.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.213310135390809037322171931381.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.213958871949474752901129776946.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.213991606285768285040679537143.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.214284159416508787494316660910.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.215789714623770039006172695183.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.216264674263551019600234488831.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.219406561997640255373602652680.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.222011645495167193875123335182.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.222375967765486859325030769323.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.222787662019588764068739545348.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.223820429713813635989317953155.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.223974347906907643959074454382.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.227095897438408080479909944265.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.227138063895124854813342282950.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.228261392162475231906819103830.dcm
|           |-- 1.3.6.1.4.1.14519.5.2.1.7009.9004.231948155294034708030177713851.dcm

**Comment by jsilter** [comment]
Documentation is available in README:
https://github.com/reginabarzilaygroup/Sybil/blob/main/README.md

and the wiki:
https://github.com/reginabarzilaygroup/Sybil/wiki
