### ISSUE TITLE
ask the two file data_splits.p corrupted_img_paths.pkl

### ISSUE THREAD

**Issue by liujun0621** [reginabarzilaygroup/Sybil#53]
excuse me,when run train.py as follows:
 rank_zero_deprecation(
Traceback (most recent call last):
  File "/root/Sybil-main/scripts/train.py", line 415, in <module>
    train(args)
  File "/root/Sybil-main/scripts/train.py", line 359, in train
    args, get_dataset(args.dataset, "train", args)
  File "/root/Sybil-main/sybil/utils/helpers.py", line 18, in get_dataset
    return SUPPORTED_DATASETS[dataset_name](args, split)
  File "/root/Sybil-main/sybil/datasets/nlst.py", line 102, in __init__
    self.dataset = self.create_dataset(split_group)
Connection to connect.cqa1.seetacloud.com closed by remote host.reate_dataset
Connection to connect.cqa1.seetacloud.com closed.paths"]
  File "/root/Sybil-main/sybil/datasets/nlst.py", line 495, in CORRUPTED_PATHS
C:\Users\liujun>e.load(open(CORRUPTED_PATHS, "rb"))
EOFError: Ran out of input

where are the file from?
/Mounts/rbg-storage1/datasets/NLST/Shetty_et_al(Google)/data_splits.p
/Mounts/rbg-storage1/datasets/NLST/corrupted_img_paths.pkl

thanks you

**Comment by pgmikhael** [comment]
Hi,

If you're training on a different set of splits, then you can ignore the use of `data_splits.p`. This just needs some simple alteration of the code. Otherwise, I have uploaded the file [here](https://drive.google.com/file/d/1_DJK3_et7An7YZHPWtGBoC01kaQnzXXq/view?usp=share_link). 

You should ignore the use of the `corrupted_img_paths.pkl` file -- this is a result of our own download/conversion pipeline of the data, which is not likely to be relevant. Again, you can comment / remove from the nlst.py file the lines referencing that file.

**Comment by liujun0621** [comment]
when i annotation code CORRUPTED_PATHS = "/Mounts/rbg-storage1/datasets/NLST/corrupted_img_paths.pkl"
there are a lots of error,what can i do next?thanks you very much

**Comment by pgmikhael** [comment]
Hi, 

I'm not sure what "annotation code" means -- but you simply need to comment out the line that reads the file and those using it in the if-statement. This is all in the nlst.py file.

**Comment by liujun0621** [comment]
annotation code as # or '''

**Comment by liujun0621** [comment]
there are a lots of depends
as follows
Traceback (most recent call last):
  File "/root/Sybil-main/scripts/train.py", line 415, in <module>
    train(args)
  File "/root/Sybil-main/scripts/train.py", line 358, in train
    train_dataset = loaders.get_train_dataset_loader(
  File "/root/Sybil-main/sybil/utils/loading.py", line 103, in get_train_dataset_loader
    weights=train_data.weights, num_samples=len(train_data), replacement=True
AttributeError: 'NLST_Survival_Dataset' object has no attribute 'weights'

**Comment by pgmikhael** [comment]
Hi,

Yes – there are many dependencies within the code. For "weights" specifically, it is utilized with the `--class_bal` flag is set to True.
